name: Triggered After Listing Files

on:
  workflow_run:
    workflows: ["List Changed Files"]
    types:
      - completed

jobs:
  follow-up:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Echo success message
        run: echo "Previous workflow completed. Executing follow-up workflow."
